In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns',200)

In [2]:
df1=pd.read_csv('train.csv')
df2=pd.read_csv('test.csv')

In [3]:
df1

,id,bin_0,bin_1,bin_2,bin_3,bin_4,nom_0,nom_1,nom_2,nom_3,nom_4,nom_5,nom_6,nom_7,nom_8,nom_9,ord_0,ord_1,ord_2,ord_3,ord_4,ord_5,day,month,target
0,0,0.0,0.0,0.0,F,N,Red,Trapezoid,Hamster,Russia,Bassoon,de4c57ee2,a64bc7ddf,598080a91,0256c7a4b,02e7c8990,3.0,Contributor,Hot,c,U,Pw,6.0,3.0,0
1,1,1.0,1.0,0.0,F,Y,Red,Star,Axolotl,NaN,Theremin,2bb3c3e5c,3a3a936e8,1dddb8473,52ead350c,f37df64af,3.0,Grandmaster,Warm,e,X,pE,7.0,7.0,0
2,2,0.0,1.0,0.0,F,N,Red,NaN,Hamster,Canada,Bassoon,b574c9841,708248125,5ddc9a726,745b909d1,NaN,3.0,NaN,Freezing,n,P,eN,5.0,9.0,0
3,3,NaN,0.0,0.0,F,N,Red,Circle,Hamster,Finland,Theremin,673bdf1f6,23edb8da3,3a33ef960,bdaa56dd1,f9d456e57,1.0,Novice,Lava Hot,a,C,NaN,3.0,3.0,0
4,4,0.0,NaN,0.0,T,N,Red,Triangle,Hamster,Costa Rica,NaN,777d1ac2c,3a7975e46,bc9cc2a94,NaN,c5361037c,3.0,Grandmaster,Cold,h,C,OZ,5.0,12.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,599995,0.0,1.0,0.0,T,N,Red,Polygon,Axolotl,India,Theremin,014770cf0,da5014b01,a7059911d,158183c63,015c63324,3.0,Novice,Freezing,a,R,GZ,5.0,NaN,0
599996,599996,1.0,0.0,0.0,T,Y,Blue,Polygon,Dog,Costa Rica,Oboe,NaN,2023ed4ed,83bdea3a5,e9fde8fa8,a02ae6a63,2.0,Novice,Boiling Hot,n,N,sf,NaN,3.0,0
599997,599997,0.0,0.0,0.0,F,Y,Red,Circle,Axolotl,Russia,Theremin,c7dc5d460,5d7d341ac,114b1dbf3,cccbca824,40f9610c1,2.0,Contributor,Freezing,n,H,MV,7.0,5.0,0
599998,599998,1.0,1.0,0.0,F,Y,NaN,Polygon,Axolotl,NaN,Piano,4d7780407,209e1054e,fba315672,4164322bd,c1a8374a0,1.0,Master,Warm,m,X,Ey,1.0,5.0,0
599999,599999,0.0,0.0,0.0,T,N,Blue,Triangle,Dog,Russia,Theremin,17f06e644,f7706ca16,67a8d4ebb,NaN,e2aea7784,1.0,Contributor,Boiling Hot,b,O,uI,5.0,8.0,0

In [4]:
df2

,id,bin_0,bin_1,bin_2,bin_3,bin_4,nom_0,nom_1,nom_2,nom_3,nom_4,nom_5,nom_6,nom_7,nom_8,nom_9,ord_0,ord_1,ord_2,ord_3,ord_4,ord_5,day,month
0,600000,0.0,0.0,0.0,F,Y,Blue,Polygon,Axolotl,Finland,Piano,52f6dd16c,147d704e4,8d857a0a1,ca9ad1d4b,fced9e114,3.0,Novice,Boiling Hot,f,U,oU,3.0,9.0
1,600001,0.0,0.0,0.0,F,Y,Red,Circle,Lion,Russia,Bassoon,691ebeae8,8653dcc2e,67a8d4ebb,060a21580,7ca8775da,1.0,Novice,Cold,n,N,NaN,2.0,8.0
2,600002,0.0,0.0,0.0,F,Y,Blue,Circle,Axolotl,Russia,Theremin,81f792c16,6cdda499e,69403e18c,165e81a00,5940334c9,1.0,Expert,Warm,i,N,DN,2.0,6.0
3,600003,1.0,0.0,0.0,F,N,Red,Polygon,Axolotl,Costa Rica,Bassoon,c9134205b,acbca4827,cb681246b,77d41330d,6fbdeefc8,1.0,Expert,Hot,m,B,AG,1.0,6.0
4,600004,0.0,0.0,1.0,F,Y,Red,Circle,NaN,Finland,Theremin,f0f100f57,6f800b9af,cd9feb5c6,2218d9dfe,2a27c8fde,1.0,Contributor,Lava Hot,o,J,DT,3.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399995,999995,0.0,0.0,1.0,T,N,Red,Trapezoid,Axolotl,Costa Rica,Theremin,92fb4c0dc,633bdcfd0,3ef3018d3,c1a4acfaf,45a68dd2e,2.0,Expert,Warm,n,R,dp,2.0,12.0
399996,999996,0.0,0.0,0.0,F,N,Red,Polygon,Dog,Russia,Theremin,8bd03e713,7c241cd40,f74f0b894,220190c9e,e48348d66,1.0,Contributor,NaN,n,X,US,1.0,5.0
399997,999997,0.0,0.0,1.0,T,N,Red,Triangle,Hamster,NaN,Theremin,6924d999b,18d43aee8,3afd3697d,cc5495ab3,47021df0d,1.0,Grandmaster,Boiling Hot,m,P,TL,1.0,6.0
399998,999998,0.0,0.0,0.0,F,Y,Red,Circle,Dog,Costa Rica,Theremin,3e0230528,0c073adc7,3600c6e91,32b33a4b4,e4bf32721,3.0,Novice,Lava Hot,h,L,DI,2.0,11.0
399999,999999,0.0,0.0,1.0,F,N,Blue,Circle,Lion,Finland,Bassoon,0568087f1,29b2ef583,69238b544,dda9ca69e,4d921f911,3.0,Contributor,Freezing,c,N,vx,3.0,6.0

In [5]:
df1['bin_4'].value_counts(normalize=True)

N    0.536717
Y    0.463283
Name: bin_4, dtype: float64

In [6]:
df1['nom_0']=df1['nom_0'].fillna('Red')
df1['nom_1']=df1['nom_1'].fillna('Triangle')
df1['nom_2']=df1['nom_2'].fillna('Hamster')
df1['nom_3']=df1['nom_3'].fillna('India')
df1['nom_4']=df1['nom_4'].fillna('Theremin')


df1['ord_0']=df1['ord_0'].fillna('1')
df1['ord_1']=df1['ord_1'].fillna('Novice')
df1['ord_2']=df1['ord_2'].fillna('Freezing')

df1['day']=df1['day'].fillna('3')

df1['month']=df1['month'].fillna('8')


df1['bin_0']=df1['bin_0'].fillna('0')
df1['bin_1']=df1['bin_1'].fillna('0')
df1['bin_2']=df1['bin_2'].fillna('0')
df1['bin_3']=df1['bin_3'].fillna('F')
df1['bin_4']=df1['bin_4'].fillna('N')

df1['bin_3']=df1['bin_3'].replace('F','0')
df1['bin_3']=df1['bin_3'].replace('T','1')
df1['bin_4']=df1['bin_4'].replace('N','0')
df1['bin_4']=df1['bin_4'].replace('Y','1')

In [7]:
df1.drop(['nom_5','nom_6','nom_7','nom_8','nom_9','ord_3','ord_4','ord_5'],axis=1,inplace=True)

In [8]:
df1.isnull().sum()

id        0
bin_0     0
bin_1     0
bin_2     0
bin_3     0
bin_4     0
nom_0     0
nom_1     0
nom_2     0
nom_3     0
nom_4     0
ord_0     0
ord_1     0
ord_2     0
day       0
month     0
target    0
dtype: int64

In [9]:
df2.isnull().sum()

id           0
bin_0    11901
bin_1    12038
bin_2    11972
bin_3    11951
bin_4    11951
nom_0    12062
nom_1    11947
nom_2    12179
nom_3    12176
nom_4    11993
nom_5    11912
nom_6    12012
nom_7    12003
nom_8    11956
nom_9    12060
ord_0    11893
ord_1    12167
ord_2    12105
ord_3    12053
ord_4    11933
ord_5    12047
day      12025
month    11984
dtype: int64

In [10]:
df2['month'].value_counts(normalize=True)

8.0     0.137293
3.0     0.122065
5.0     0.118284
12.0    0.116846
6.0     0.103864
7.0     0.091824
1.0     0.089200
11.0    0.088050
2.0     0.069399
9.0     0.034669
4.0     0.024661
10.0    0.003845
Name: month, dtype: float64

In [11]:
df2['nom_0']=df2['nom_0'].fillna('Red')
df2['nom_1']=df2['nom_1'].fillna('Triangle')
df2['nom_2']=df2['nom_2'].fillna('Hamster')
df2['nom_3']=df2['nom_3'].fillna('India')
df2['nom_4']=df2['nom_4'].fillna('Theremin')


df2['ord_0']=df2['ord_0'].fillna('1')
df2['ord_1']=df2['ord_1'].fillna('Novice')
df2['ord_2']=df2['ord_2'].fillna('Freezing')

df2['day']=df2['day'].fillna('3')

df2['month']=df2['month'].fillna('8')


df2['bin_0']=df2['bin_0'].fillna('0')
df2['bin_1']=df2['bin_1'].fillna('0')
df2['bin_2']=df2['bin_2'].fillna('0')
df2['bin_3']=df2['bin_3'].fillna('F')
df2['bin_4']=df2['bin_4'].fillna('N')

df2['bin_3']=df2['bin_3'].replace('F','0')
df2['bin_3']=df2['bin_3'].replace('T','1')
df2['bin_4']=df2['bin_4'].replace('N','0')
df2['bin_4']=df2['bin_4'].replace('Y','1')

In [12]:
df2.drop(['nom_5','nom_6','nom_7','nom_8','nom_9','ord_3','ord_4','ord_5'],axis=1,inplace=True)

In [13]:
df1

,id,bin_0,bin_1,bin_2,bin_3,bin_4,nom_0,nom_1,nom_2,nom_3,nom_4,ord_0,ord_1,ord_2,day,month,target
0,0,0.0,0.0,0.0,0,0,Red,Trapezoid,Hamster,Russia,Bassoon,3.0,Contributor,Hot,6.0,3.0,0
1,1,1.0,1.0,0.0,0,1,Red,Star,Axolotl,India,Theremin,3.0,Grandmaster,Warm,7.0,7.0,0
2,2,0.0,1.0,0.0,0,0,Red,Triangle,Hamster,Canada,Bassoon,3.0,Novice,Freezing,5.0,9.0,0
3,3,0,0.0,0.0,0,0,Red,Circle,Hamster,Finland,Theremin,1.0,Novice,Lava Hot,3.0,3.0,0
4,4,0.0,0,0.0,1,0,Red,Triangle,Hamster,Costa Rica,Theremin,3.0,Grandmaster,Cold,5.0,12.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,599995,0.0,1.0,0.0,1,0,Red,Polygon,Axolotl,India,Theremin,3.0,Novice,Freezing,5.0,8,0
599996,599996,1.0,0.0,0.0,1,1,Blue,Polygon,Dog,Costa Rica,Oboe,2.0,Novice,Boiling Hot,3,3.0,0
599997,599997,0.0,0.0,0.0,0,1,Red,Circle,Axolotl,Russia,Theremin,2.0,Contributor,Freezing,7.0,5.0,0
599998,599998,1.0,1.0,0.0,0,1,Red,Polygon,Axolotl,India,Piano,1.0,Master,Warm,1.0,5.0,0
599999,599999,0.0,0.0,0.0,1,0,Blue,Triangle,Dog,Russia,Theremin,1.0,Contributor,Boiling Hot,5.0,8.0,0

In [14]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 17 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   id      600000 non-null  int64
 1   bin_0   600000 non-null  object
 2   bin_1   600000 non-null  object
 3   bin_2   600000 non-null  object
 4   bin_3   600000 non-null  object
 5   bin_4   600000 non-null  object
 6   nom_0   600000 non-null  object
 7   nom_1   600000 non-null  object
 8   nom_2   600000 non-null  object
 9   nom_3   600000 non-null  object
 10  nom_4   600000 non-null  object
 11  ord_0   600000 non-null  object
 12  ord_1   600000 non-null  object
 13  ord_2   600000 non-null  object
 14  day     600000 non-null  object
 15  month   600000 non-null  object
 16  target  600000 non-null  int64
dtypes: int64(2), object(15)
memory usage: 77.8+ MB

In [15]:
df1[['bin_0','bin_1','bin_2','bin_3','bin_4','ord_0']]=df1[['bin_0','bin_1','bin_2','bin_3','bin_4','ord_0']].astype(float)

In [16]:
df=pd.get_dummies(df1)

In [17]:
df

,id,bin_0,bin_1,bin_2,bin_3,bin_4,ord_0,target,nom_0_Blue,nom_0_Green,nom_0_Red,nom_1_Circle,nom_1_Polygon,nom_1_Square,nom_1_Star,nom_1_Trapezoid,nom_1_Triangle,nom_2_Axolotl,nom_2_Cat,nom_2_Dog,nom_2_Hamster,nom_2_Lion,nom_2_Snake,nom_3_Canada,nom_3_China,nom_3_Costa Rica,nom_3_Finland,nom_3_India,nom_3_Russia,nom_4_Bassoon,nom_4_Oboe,nom_4_Piano,nom_4_Theremin,ord_1_Contributor,ord_1_Expert,ord_1_Grandmaster,ord_1_Master,ord_1_Novice,ord_2_Boiling Hot,ord_2_Cold,ord_2_Freezing,ord_2_Hot,ord_2_Lava Hot,ord_2_Warm,day_1.0,day_2.0,day_3.0,day_4.0,day_5.0,day_6.0,day_7.0,day_3,month_1.0,month_2.0,month_3.0,month_4.0,month_5.0,month_6.0,month_7.0,month_8.0,month_9.0,month_10.0,month_11.0,month_12.0,month_8
0,0,0.0,0.0,0.0,0.0,0.0,3.0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1,1,1.0,1.0,0.0,0.0,1.0,3.0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0
2,2,0.0,1.0,0.0,0.0,0.0,3.0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,3,0.0,0.0,0.0,0.0,0.0,1.0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
4,4,0.0,0.0,0.0,1.0,0.0,3.0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,599995,0.0,1.0,0.0,1.0,0.0,3.0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
599996,599996,1.0,0.0,0.0,1.0,1.0,2.0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
599997,599997,0.0,0.0,0.0,0.0,1.0,2.0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0
599998,599998,1.0,1.0,0.0,0.0,1.0,1.0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
599999,599999,0.0,0.0,0.0,1.0,0.0,1.0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [18]:
x=df.drop('target',axis=1)
y=df['target']

In [19]:
from sklearn.model_selection import train_test_split as tts
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score

In [20]:
x_train,x_test,y_train,y_test=tts(x,y,test_size=0.25,random_state=42)

In [21]:
gbc=GradientBoostingClassifier()
gbc.fit(x_train,y_train)
y_pred=gbc.predict(x_test)

In [22]:
accuracy_score(y_test,y_pred)

0.81362

In [23]:
df2[['bin_0','bin_1','bin_2','bin_3','bin_4','ord_0']]=df2[['bin_0','bin_1','bin_2','bin_3','bin_4','ord_0']].astype(float)

In [24]:
a=pd.get_dummies(df2)

In [25]:
tahmin=gbc.predict(a)

In [26]:
df2['target']=tahmin

In [27]:
df2[['id','target']].to_csv('category.csv',index=False)

In [28]:
df2['target'].value_counts()

0    398089
1      1911
Name: target, dtype: int64