In [1]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup

In [2]:
source1=requests.get('https://www.hepsiemlak.com/istanbul-kiralik').text
source2=requests.get('https://www.hepsiemlak.com/istanbul-kiralik?page=2').text
source3=requests.get('https://www.hepsiemlak.com/istanbul-kiralik?page=3').text
source4=requests.get('https://www.hepsiemlak.com/istanbul-kiralik?page=4').text
source5=requests.get('https://www.hepsiemlak.com/istanbul-kiralik?page=5').text
source6=requests.get('https://www.hepsiemlak.com/istanbul-kiralik?page=6').text
source7=requests.get('https://www.hepsiemlak.com/istanbul-kiralik?page=7').text
source8=requests.get('https://www.hepsiemlak.com/istanbul-kiralik?page=8').text
source9=requests.get('https://www.hepsiemlak.com/istanbul-kiralik?page=9').text
source10=requests.get('https://www.hepsiemlak.com/istanbul-kiralik?page=10').text
source=source1+source2+source3+source4+source5+source6+source7+source8+source9+source10

In [3]:
soup=BeautifulSoup(source,'html.parser')

In [4]:
soup.beautify

In [5]:
container=soup.find_all("ul",{"class":"list-items-container"})

In [6]:
fiyat=soup.findAll("span",{"class":"list-view-price"})
yas=soup.findAll("span",{"class":"celly buildingAge"})
kat=soup.findAll("span",{"class":"celly floortype"})
boyut=soup.findAll("span",{"class":"celly houseRoomCount"})
alan=soup.findAll("span",{"class":"celly squareMeter list-view-size"})

In [7]:
f=[]
y=[]
k=[]
b=[]
a=[]

In [8]:
for span in fiyat:
    print(span.text)
    f.append(span.text)

              30.000
              TL

              32.000
              TL

              15.000
              TL

              35.000
              TL

              110.000
              TL

              6.100
              TL

              16.000
              TL

              10.000
              TL

              12.500
              TL

              14.000
              TL

              8.250
              TL

              50.000
              TL

              10.000
              TL

              6.000
              TL

              15.000
              TL

              12.000
              TL

              25.000
              TL

              23.000
              TL

              28.500
              TL

              16.000
              TL

              28.500
              TL

              25.000
              TL

              11.500
              TL

              13.500
              TL

              14.950
              TL

              18.000
              TL

              40.000
              TL

              45.000
              TL

              12.000
              TL

              17.000
              TL

              12.500
              TL

              39.000
              TL

              6.750
              TL

              13.500
              TL

              8.500
              TL

              27.500
              TL

              7.500
              TL

              17.500
              TL

              45.000
              TL

              9.700
              TL

              77.500
              TL

              13.500
              TL

              11.000
              TL

              15.000
              TL

              7.000
              TL

              12.500
              TL

              6.000
              TL

              22.000
              TL

              15.000
              TL

              5.000
              TL

              26.000
              TL

              12.000
              TL

              17.000
              TL

              7.250
              TL

              7.500
              TL

              18.000
              TL

              10.000
              TL

              6.800
              TL

              8.650
              TL

              13.500
              TL

              7.000
              TL

              7.500
              TL

              6.000
              TL

              27.000
              TL

              7.000
              TL

              4.500
              TL

              26.000
              TL

              30.000
              TL

              10.000
              TL

              10.000
              TL

              20.000
              TL

              50.000
              TL

              32.000
              TL

              7.000
              TL

              9.500
              TL

              12.000
              TL

              45.000
              TL

              15.000
              TL

              360.000
              TL

              11.000
              TL

              35.000
              TL

              13.500
              TL

              15.000
              TL

              12.000
              TL

              27.000
              TL

              13.500
              TL

              10.000
              TL

              30.000
              TL

              170.000
              TL

              16.150
              TL

              14.000
              TL

              5.750
              TL

              30.000
              TL

              11.750
              TL

              20.000
              TL

              10.000
              TL

              17.000
              TL

              28.500
              TL

              8.250
              TL

              10.000
              TL

              30.000
              TL

              8.000
              TL

              7.000
              TL

              8.000
              TL

              18.300
              TL

              9.000
              TL

              25.000
              TL

              14.000
              TL

              6.500
              TL

              4.500
              TL

              11.000
              TL

              10.000
              TL

              26.000
              TL

              17.500
              TL

              20.000
              TL

              12.500
              TL

              25.000
              TL

              11.000
              TL

              15.000
              TL

              24.000
              TL

              6.750
              TL

              10.000
              TL

              15.000
              TL

              30.000
              TL

              8.000
              TL

              14.000
              TL

              18.500
              TL

              10.000
              TL

              9.000
              TL

              15.000
              TL

              7.500
              TL

              170.000
              TL

              10.000
              TL

              6.500
              TL

              15.500
              TL

              27.000
              TL

              7.500
              TL

              8.000
              TL

              50.000
              TL

              8.600
              TL

              19.000
              TL

              4.500
              TL

              9.000
              TL

              10.000
              TL

              26.000
              TL

              12.500
              TL

              8.000
              TL

              8.000
              TL

              50.000
              TL

              15.000
              TL

              6.500
              TL

              22.000
              TL

              20.000
              TL

              12.000
              TL

              7.900
              TL

              7.500
              TL

              24.000
              TL

              13.500
              TL

              6.000
              TL

              9.400
              TL

              7.500
              TL

              4.500
              TL

              9.000
              TL

              24.000
              TL

              20.000
              TL

              17.000
              TL

              2.750
              TL

              30.000
              TL

              21.000
              TL

              35.000
              TL

              43.000
              TL

              9.000
              TL

              5.750
              TL

              9.000
              TL

              7.000
              TL

              9.000
              TL

              18.000
              TL

              13.000
              TL

              7.000
              TL

              27.500
              TL

              15.000
              TL

              54.500
              TL

              6.250
              TL

              4.500
              TL

              5.000
              TL

              8.500
              TL

              10.000
              TL

              32.000
              TL

              10.000
              TL

              15.000
              TL

              6.000
              TL

              9.500
              TL

              25.000
              TL

              11.200
              TL

              15.000
              TL

              6.000
              TL

              12.000
              TL

              20.500
              TL

              12.000
              TL

              12.000
              TL

              11.000
              TL

              55.000
              TL

              7.000
              TL

              4.500
              TL

              9.500
              TL

              6.000
              TL

              9.000
              TL

              37.500
              TL

              7.000
              TL

              55.000
              TL

              135.000
              TL

              35.000
              TL

              7.500
              TL

              7.200
              TL

              6.800
              TL

              55.000
              TL

              55.000
              TL

              14.000
              TL

              6.000
              TL

              11.000
              TL

              13.500
              TL

              7.500
              TL

              13.500
              TL

              6.900
              TL

              35.000
              TL

              8.000
              TL

              5.500
              TL

              40.250
              TL

              10.000
              TL

              13.250
              TL

              11.000
              TL

              8.500
              TL

              23.000
              TL

              15.000
              TL

              35.000
              TL

              55.000
              TL

              19.200
              TL

              8.100
              TL

              12.000
              TL

              10.000
              TL

In [9]:
for span in yas:
    print(span.text)
    y.append(span.text)

5 Yaşında
16 Yaşında
13 Yaşında
3 Yaşında
11 Yaşında
7 Yaşında
6 Yaşında
4 Yaşında
35 Yaşında
4 Yaşında
20 Yaşında
3 Yaşında
40 Yaşında
7 Yaşında
35 Yaşında
19 Yaşında
7 Yaşında
Sıfır Bina
1 Yaşında
6 Yaşında
1 Yaşında
7 Yaşında
30 Yaşında
45 Yaşında
20 Yaşında
65 Yaşında
40 Yaşında
90 Yaşında
13 Yaşında
7 Yaşında
8 Yaşında
7 Yaşında
12 Yaşında
40 Yaşında
23 Yaşında
35 Yaşında
7 Yaşında
4 Yaşında
36 Yaşında
10 Yaşında
10 Yaşında
33 Yaşında
17 Yaşında
Sıfır Bina
1 Yaşında
1 Yaşında
35 Yaşında
Sıfır Bina
55 Yaşında
10 Yaşında
5 Yaşında
5 Yaşında
20 Yaşında
Sıfır Bina
7 Yaşında
5 Yaşında
40 Yaşında
25 Yaşında
31 Yaşında
27 Yaşında
16 Yaşında
25 Yaşında
8 Yaşında
4 Yaşında
4 Yaşında
5 Yaşında
10 Yaşında
45 Yaşında
20 Yaşında
Sıfır Bina
35 Yaşında
4 Yaşında
1 Yaşında
5 Yaşında
4 Yaşında
35 Yaşında
11 Yaşında
Sıfır Bina
8 Yaşında
15 Yaşında
30 Yaşında
18 Yaşında
30 Yaşında
25 Yaşında
6 Yaşında
18 Yaşında
Sıfır Bina
23 Yaşında
17 Yaşında
Sıfır Bina
5 Yaşında
20 Yaşında
10 Yaşında
25 Yaşında
Sıfır Bina
5 Yaşında
7 Yaşında
12 Yaşında
33 Yaşında
35 Yaşında
4 Yaşında
Sıfır Bina
3 Yaşında
35 Yaşında
3 Yaşında
38 Yaşında
25 Yaşında
6 Yaşında
35 Yaşında
6 Yaşında
Sıfır Bina
6 Yaşında
5 Yaşında
35 Yaşında
10 Yaşında
5 Yaşında
4 Yaşında
Sıfır Bina
21 Yaşında
15 Yaşında
23 Yaşında
20 Yaşında
11 Yaşında
Sıfır Bina
25 Yaşında
20 Yaşında
15 Yaşında
Sıfır Bina
15 Yaşında
25 Yaşında
8 Yaşında
18 Yaşında
35 Yaşında
30 Yaşında
25 Yaşında
50 Yaşında
5 Yaşında
40 Yaşında
50 Yaşında
28 Yaşında
31 Yaşında
5 Yaşında
1 Yaşında
23 Yaşında
50 Yaşında
30 Yaşında
Sıfır Bina
38 Yaşında
25 Yaşında
3 Yaşında
Sıfır Bina
16 Yaşında
4 Yaşında
3 Yaşında
5 Yaşında
33 Yaşında
15 Yaşında
18 Yaşında
10 Yaşında
15 Yaşında
8 Yaşında
20 Yaşında
30 Yaşında
21 Yaşında
7 Yaşında
2 Yaşında
Sıfır Bina
30 Yaşında
10 Yaşında
5 Yaşında
30 Yaşında
38 Yaşında
23 Yaşında
4 Yaşında
19 Yaşında
2 Yaşında
8 Yaşında
Sıfır Bina
25 Yaşında
Sıfır Bina
25 Yaşında
4 Yaşında
4 Yaşında
25 Yaşında
25 Yaşında
35 Yaşında
1 Yaşında
15 Yaşında
45 Yaşında
4 Yaşında
25 Yaşında
6 Yaşında
4 Yaşında
22 Yaşında
12 Yaşında
25 Yaşında
Sıfır Bina
3 Yaşında
31 Yaşında
30 Yaşında
8 Yaşında
20 Yaşında
Sıfır Bina
5 Yaşında
6 Yaşında
3 Yaşında
2 Yaşında
10 Yaşında
17 Yaşında
5 Yaşında
5 Yaşında
8 Yaşında
5 Yaşında
10 Yaşında
25 Yaşında
7 Yaşında
7 Yaşında
35 Yaşında
22 Yaşında
26 Yaşında
30 Yaşında
25 Yaşında
32 Yaşında
13 Yaşında
30 Yaşında
1 Yaşında
7 Yaşında
5 Yaşında
Sıfır Bina
25 Yaşında
40 Yaşında
18 Yaşında
7 Yaşında
2 Yaşında
2 Yaşında
50 Yaşında
9 Yaşında
25 Yaşında
9 Yaşında
2 Yaşında

In [10]:
for span in kat:
    print(span.text)
    k.append(span.text)

                      10. Kat

                      4. Kat

                      6. Kat

                      21 ve üzeri

                      Bahçe Katı

                      Kot 1

                      5. Kat

                      3. Kat

                      3. Kat

                      7. Kat

                      1. Kat

                      12. Kat

                      4. Kat

                      Teras Katı

                      2. Kat

                      3. Kat

                      6. Kat

                      3. Kat

                      17. Kat

                      5. Kat

                      17. Kat

                      6. Kat

                      Giriş Katı

                      Ara Kat

                      2. Kat

                      1. Kat

                      1. Kat

                      2. Kat

                      3. Kat

                      1. Kat

                      17. Kat

                      3. Kat

                      5. Kat

                      2. Kat

                      8. Kat

                      5. Kat

                      Ara Kat

                      Çatı Katı

                      3. Kat

                      En Üst Kat



                      3. Kat

                      Kot 1

                      3. Kat

                      1. Kat

                      2. Kat

                      1. Kat

                      21 ve üzeri

                      3. Kat

                      Yüksek Giriş



                      4. Kat

                      En Üst Kat

                      21 ve üzeri

                      5. Kat

                      7. Kat

                      4. Kat

                      5. Kat

                      7. Kat

                      3. Kat

                      5. Kat

                      1. Kat

                      En Üst Kat

                      10. Kat

                      3. Kat

                      1. Kat

                      Bahçe Katı

                      5. Kat

                      4. Kat

                      1. Kat

                      2. Kat

                      9. Kat

                      Bahçe Katı

                      Ara Kat

                      2. Kat

                      1. Kat

                      2. Kat

                      4. Kat



                      Ara Kat



                      Giriş Katı

                      4. Kat

                      8. Kat

                      15. Kat

                      Yüksek Giriş

                      Ara Kat

                      3. Kat

                      8. Kat

                      4. Kat

                      5. Kat

                      Ara Kat



                      Giriş Katı

                      21 ve üzeri



                      Bahçe Katı

                      1. Kat

                      2. Kat

                      1. Kat

                      Bahçe Katı

                      1. Kat

                      Yüksek Giriş

                      1. Kat

                      1. Kat

                      3. Kat

                      3. Kat

                      2. Kat

                      2. Kat

                      Yüksek Giriş

                      9. Kat

                      4. Kat

                      Bahçe Katı

                      1. Kat

                      3. Kat

                      6. Kat

                      9. Kat

                      Yüksek Giriş

                      2. Kat

                      Çatı Katı

                      11. Kat

                      4. Kat

                      6. Kat

                      Ara Kat

                      Ara Kat

                      3. Kat

                      7. Kat

                      4. Kat

                      9. Kat

                      1. Kat

                      Kot 2

                      8. Kat

                      4. Kat

                      2. Kat

                      9. Kat

                      1. Kat

                      Bahçe Katı

                      3. Kat

                      Teras Katı

                      11. Kat

                      1. Kat

                      1. Kat

                      5. Kat

                      En Üst Kat

                      7. Kat

                      2. Kat

                      2. Kat

                      3. Kat

                      En Üst Kat

                      4. Kat

                      15. Kat

                      2. Kat

                      3. Kat

                      5. Kat

                      12. Kat

                      2. Kat

                      Çatı Katı

                      4. Kat

                      20. Kat

                      3. Kat

                      1. Kat

                      Kot 1

                      3. Kat

                      5. Kat

                      1. Kat

                      14. Kat

                      Ara Kat

                      Ara Kat

                      2. Kat

                      20. Kat

                      2. Kat

                      1. Kat

                      5. Kat

                      4. Kat

                      4. Kat

                      Teras Katı

                      7. Kat

                      Giriş Katı

                      9. Kat

                      1. Kat

                      2. Kat

                      16. Kat

                      6. Kat

                      2. Kat

                      Yüksek Giriş

                      Bahçe Katı

                      Ara Kat



                      3. Kat

                      1. Kat

                      Giriş Katı

                      1. Kat

                      5. Kat

                      3. Kat

                      5. Kat

                      2. Kat

                      2. Kat

                      Ara Kat

                      4. Kat

                      4. Kat

                      Ara Kat

                      4. Kat

                      Bahçe Katı

                      2. Kat

                      2. Kat

                      Teras Katı

                      1. Kat

                      5. Kat

                      2. Kat

                      21 ve üzeri

                      Bahçe Katı

                      Bahçe Katı

                      1. Kat

                      Bahçe Katı

                      Bahçe Katı

                      9. Kat

                      9. Kat

                      3. Kat

                      5. Kat

                      5. Kat

                      3. Kat

                      Bahçe Katı

                      7. Kat

                      4. Kat



                      7. Kat

                      6. Kat

                      Ara Kat

                      4. Kat

                      5. Kat

                      Bahçe Katı

                      12. Kat

                      2. Kat

                      8. Kat

                      21 ve üzeri

                      4. Kat

                      Ara Kat

                      1. Kat

                      1. Kat

                      3. Kat

In [11]:
for span in boyut:
    print(span.text)
    b.append(span.text)

2 + 1
4 + 1
1 + 1
1 + 1
4 + 2
2 + 1
1 + 1
2 + 1
3 + 1
3 + 1
2 + 1
3 + 1
3 + 1
1 + 1
3 + 1
3 + 1
3 + 1
2 + 2
2 + 1
1 + 1
2 + 1
3 + 1
1 + 1
2 + 1
2 + 1
2 + 1
2 + 1
4 + 1
3 + 1
3 + 1
3 + 1
7 + 2
2 + 1
3 + 1
3 + 1
2 + 1
2 + 1
1 + 1
3 + 1
4 + 1
5 + 2
2 + 1
2 + 1
2 + 1
1 + 1
2 + 1
2 + 1
1 + 1
4 + 1
Stüdyo
3 + 1
3 + 1
3 + 1
1 + 1
3 + 1
Stüdyo
2 + 1
2 + 1
4 + 2
3 + 1
2 + 1
2 + 1
2 + 1
2 + 1
2 + 1
2 + 1
2 + 1
3 + 1
3 + 1
2 + 1
3 + 1
3 + 1
2 + 2
3 + 1
2 + 1
3 + 1
4 + 1
4 + 1
7 + 2
3 + 1
7 + 1
3 + 1
3 + 1
4 + 1
2 + 1
3 + 1
2 + 1
5 + 1
4 + 1
3 + 1
1 + 1
Stüdyo
5 + 2
3 + 1
3 + 1
3 + 2
1 + 1
3 + 1
3 + 1
3 + 1
2 + 1
3 + 1
1 + 1
3 + 1
3 + 1
3 + 1
2 + 1
3 + 1
1 + 1
2 + 1
1 + 1
4 + 2
5 + 1
2 + 1
3 + 1
2 + 1
1 + 1
3 + 1
3 + 1
1 + 1
1 + 1
3 + 1
3 + 1
4 + 1
1 + 1
3 + 1
3 + 1
1 + 1
3 + 1
3 + 1
2 + 1
4 + 1
3 + 1
3 + 1
3 + 1
3 + 1
1 + 1
2 + 1
6 + 1
3 + 1
2 + 1
2 + 1
1 + 1
2 + 1
3 + 1
3 + 1
3 + 1
2 + 1
2 + 1
3 + 1
1 + 1
2 + 1
Stüdyo
4 + 2
1 + 1
2 + 1
1 + 1
2 + 1
1 + 1
3 + 1
2 + 1
Stüdyo
2 + 1
3 + 1
2 + 1
Stüdyo
Stüdyo
3 + 1
1 + 1
3 + 1
3 + 1
3 + 1
1 + 1
1 + 1
2 + 1
2 + 1
1 + 1
2 + 1
3 + 1
3 + 1
3 + 1
3 + 1
1 + 1
2 + 1
2 + 1
2 + 1
2 + 1
4 + 2
3 + 1
1 + 1
2 + 1
2 + 1
1 + 1
1 + 1
1 + 1
3 + 1
2 + 1
1 + 1
2 + 1
2 + 1
276 + 1
4 + 1
2 + 1
1 + 1
3 + 1
3 + 1
2 + 1
1 + 1
3 + 1
4 + 1
5 + 2
5 + 1
1 + 1
2 + 1
2 + 1
3 + 1
3 + 1
3 + 1
2 + 1
3 + 1
2 + 1
2 + 1
3 + 1
1 + 1
3 + 1
1 + 1
Stüdyo
1 + 1
3 + 1
3 + 1
2 + 1
3 + 1
4 + 2
2 + 1
1 + 1
4 + 2
2 + 1
2 + 1
1 + 1
Stüdyo

In [12]:
for span in alan:
    print(span.text)
    a.append(span.text)

                          115 m2

                          180 m2

                          85 m2

                          90 m2

                          470 m2

                          85 m2

                          94 m2

                          80 m2

                          140 m2

                          120 m2

                          80 m2

                          120 m2

                          110 m2

                          80 m2

                          110 m2

                          150 m2

                          117 m2

                          156 m2

                          101 m2

                          94 m2

                          101 m2

                          117 m2

                          80 m2

                          100 m2

                          75 m2

                          150 m2

                          100 m2

                          230 m2

                          130 m2

                          165 m2

                          150 m2

                          450 m2

                          75 m2

                          135 m2

                          145 m2

                          125 m2

                          90 m2

                          125 m2

                          155 m2

                          155 m2

                          388 m2

                          120 m2

                          95 m2

                          85 m2

                          55 m2

                          75 m2

                          75 m2

                          80 m2

                          159 m2

                          55 m2

                          185 m2

                          125 m2

                          180 m2

                          72 m2

                          135 m2

                          69 m2

                          120 m2

                          90 m2

                          220 m2

                          120 m2

                          84 m2

                          90 m2

                          90 m2

                          160 m2

                          85 m2

                          110 m2

                          165 m2

                          150 m2

                          110 m2

                          85 m2

                          130 m2

                          155 m2

                          180 m2

                          135 m2

                          100 m2

                          130 m2

                          200 m2

                          141 m2

                          1.000 m2

                          155 m2

                          350 m2

                          145 m2

                          175 m2

                          240 m2

                          145 m2

                          145 m2

                          100 m2

                          300 m2

                          350 m2

                          150 m2

                          80 m2

                          45 m2

                          400 m2

                          160 m2

                          180 m2

                          250 m2

                          65 m2

                          170 m2

                          115 m2

                          130 m2

                          130 m2

                          125 m2

                          55 m2

                          110 m2

                          125 m2

                          130 m2

                          112 m2

                          105 m2

                          58 m2

                          60 m2

                          77 m2

                          180 m2

                          164 m2

                          90 m2

                          125 m2

                          126 m2

                          85 m2

                          100 m2

                          160 m2

                          120 m2

                          55 m2

                          110 m2

                          150 m2

                          165 m2

                          77 m2

                          130 m2

                          172 m2

                          65 m2

                          165 m2

                          118 m2

                          85 m2

                          350 m2

                          120 m2

                          130 m2

                          180 m2

                          160 m2

                          60 m2

                          95 m2

                          320 m2

                          155 m2

                          100 m2

                          110 m2

                          60 m2

                          155 m2

                          140 m2

                          130 m2

                          125 m2

                          105 m2

                          170 m2

                          130 m2

                          77 m2

                          90 m2

                          65 m2

                          170 m2

                          72 m2

                          95 m2

                          120 m2

                          85 m2

                          68 m2

                          125 m2

                          100 m2

                          45 m2

                          105 m2

                          165 m2

                          90 m2

                          59 m2

                          50 m2

                          180 m2

                          70 m2

                          160 m2

                          180 m2

                          115 m2

                          58 m2

                          65 m2

                          80 m2

                          95 m2

                          81 m2

                          150 m2

                          140 m2

                          150 m2

                          150 m2

                          198 m2

                          75 m2

                          100 m2

                          100 m2

                          85 m2

                          90 m2

                          250 m2

                          130 m2

                          70 m2

                          90 m2

                          90 m2

                          100 m2

                          66 m2

                          85 m2

                          110 m2

                          85 m2

                          75 m2

                          110 m2

                          90 m2

                          105 m2

                          245 m2

                          75 m2

                          56 m2

                          130 m2

                          160 m2

                          90 m2

                          140 m2

                          140 m2

                          216 m2

                          505 m2

                          250 m2

                          80 m2

                          85 m2

                          120 m2

                          187 m2

                          187 m2

                          145 m2

                          95 m2

                          150 m2

                          85 m2

                          160 m2

                          165 m2

                          73 m2

                          145 m2

                          75 m2

                          32 m2

                          108 m2

                          150 m2

                          120 m2

                          90 m2

                          170 m2

                          200 m2

                          90 m2

                          105 m2

                          310 m2

                          110 m2

                          85 m2

                          60 m2

                          55 m2

In [13]:
d={'fiyat':f,'yas':y,'kat':k,'boyut':b,'alan':a}
df=pd.DataFrame(d)

In [14]:
df

,fiyat,yas,kat,boyut,alan
0,\n 30.000\n TL,5 Yaşında,\n 10. Kat,2 + 1,\n 115 m2
1,\n 32.000\n TL,16 Yaşında,\n 4. Kat,4 + 1,\n 180 m2
2,\n 15.000\n TL,13 Yaşında,\n 6. Kat,1 + 1,\n 85 m2
3,\n 35.000\n TL,3 Yaşında,\n 21 ve üzeri,1 + 1,\n 90 m2
4,\n 110.000\n TL,11 Yaşında,\n Bahçe Katı,4 + 2,\n 470 m2
...,...,...,...,...,...
235,\n 55.000\n TL,50 Yaşında,\n 4. Kat,4 + 2,\n 310 m2
236,\n 19.200\n TL,9 Yaşında,\n Ara Kat,2 + 1,\n 110 m2
237,\n 8.100\n TL,25 Yaşında,\n 1. Kat,2 + 1,\n 85 m2
238,\n 12.000\n TL,9 Yaşında,\n 1. Kat,1 + 1,\n 60 m2
239,\n 10.000\n TL,2 Yaşında,\n 3. Kat,Stüdyo,\n 55 m2

In [15]:
df.kat.value_counts()

\n                      1. Kat          30
\n                      3. Kat          27
\n                      2. Kat          27
\n                      4. Kat          22
\n                      5. Kat          19
\n                      Bahçe Katı      15
\n                      Ara Kat         15
\n                      9. Kat           8
\n                      7. Kat           8
\n                                       8
\n                      6. Kat           7
\n                      21 ve üzeri      6
\n                      Yüksek Giriş     6
\n                      Giriş Katı       5
\n                      8. Kat           5
\n                      En Üst Kat       5
\n                      Teras Katı       4
\n                      Çatı Katı        3
\n                      17. Kat          3
\n                      12. Kat          3
\n                      Kot 1            3
\n                      11. Kat          2
\n                      20. Kat          2
\n                      10. Kat          2
\n                      15. Kat          2
\n                      Kot 2            1
\n                      14. Kat          1
\n                      16. Kat          1
Name: kat, dtype: int64

In [16]:
df['fiyat']=df['fiyat'].str.replace('\n','')
df['kat']=df['kat'].str.replace('\n','')
df['alan']=df['alan'].str.replace('\n','')
df['fiyat']=df['fiyat'].str.replace('TL','')
df['yas']=df['yas'].str.replace('Yaşında','')
df['yas']=df['yas'].str.replace('Sıfır Bina','0')


df['alan']=df['alan'].str.replace('m2','')
df['fiyat']=df['fiyat'].str.replace('.','')
df['alan']=df['alan'].str.replace('.','')




df['fiyat']=df['fiyat'].astype(int)
df['yas']=df['yas'].astype(int)

df['alan']=df['alan'].astype(int)

C:\Users\bilal\AppData\Local\Temp\ipykernel_11040\521257146.py:10: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['fiyat']=df['fiyat'].str.replace('.','')
C:\Users\bilal\AppData\Local\Temp\ipykernel_11040\521257146.py:11: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['alan']=df['alan'].str.replace('.','')

In [17]:
df.to_csv('istanbul.csv')

In [18]:
df

      fiyat  yas                                kat   boyut  alan
0     30000    5                            10. Kat   2 + 1   115
1     32000   16                             4. Kat   4 + 1   180
2     15000   13                             6. Kat   1 + 1    85
3     35000    3                        21 ve üzeri   1 + 1    90
4    110000   11                         Bahçe Katı   4 + 2   470
..      ...  ...                                ...     ...   ...
235   55000   50                             4. Kat   4 + 2   310
236   19200    9                            Ara Kat   2 + 1   110
237    8100   25                             1. Kat   2 + 1    85
238   12000    9                             1. Kat   1 + 1    60
239   10000    2                             3. Kat  Stüdyo    55

[240 rows x 5 columns]

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   fiyat   240 non-null    int32
 1   yas     240 non-null    int32
 2   kat     240 non-null    object
 3   boyut   240 non-null    object
 4   alan    240 non-null    int32
dtypes: int32(3), object(2)
memory usage: 6.7+ KB

In [20]:
df=pd.get_dummies(df,drop_first=True)

In [21]:
df

,fiyat,yas,alan,kat_ 1. Kat,kat_ 10. Kat,kat_ 11. Kat,kat_ 12. Kat,kat_ 14. Kat,kat_ 15. Kat,kat_ 16. Kat,...,boyut_3 + 1,boyut_3 + 2,boyut_4 + 1,boyut_4 + 2,boyut_5 + 1,boyut_5 + 2,boyut_6 + 1,boyut_7 + 1,boyut_7 + 2,boyut_Stüdyo
0,30000,5,115,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,32000,16,180,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,15000,13,85,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,35000,3,90,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,110000,11,470,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,55000,50,310,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
236,19200,9,110,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
237,8100,25,85,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
238,12000,9,60,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
239,10000,2,55,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [22]:
x=df.drop('fiyat',axis=1)
y=df['fiyat']

In [23]:
#from pycaret.regression import*

In [24]:
#exp_name=setup(data=df,target='fiyat')

In [25]:
#best=compare_models()

In [26]:
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split

In [27]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2,random_state=13)

In [28]:
gbr=GradientBoostingRegressor()

In [29]:
öğren=gbr.fit(x_train,y_train)

In [30]:
tahmin=öğren.predict(x_test)

In [31]:
(mean_squared_error(y_test,tahmin))**0.5

39649.59915444927

In [32]:
(r2_score(y_test,tahmin))

0.46712774932367873

In [33]:
from sklearn.linear_model import LinearRegression

In [34]:
lr=LinearRegression()
regmodel=lr.fit(x_train,y_train)

In [35]:
y_pretest=regmodel.predict(x_test)

In [36]:
(mean_squared_error(y_test,y_pretest))**0.5

25055.755746056846

In [37]:
r2_score(y_test,y_pretest)

0.7872054424598812

In [38]:
from sklearn.linear_model import Ridge,Lasso

In [39]:
R=Ridge()
R.fit(x_train,y_train)
y_pred_ridge=R.predict(x_test)

In [40]:
(mean_squared_error(y_test,y_pred_ridge))**0.5

29125.74876115645

In [41]:
r2_score(y_test,y_pred_ridge) ## en başarılı

0.7124590516961835

In [42]:
L=Lasso()
L.fit(x_train,y_train)
y_pred_lasso=L.predict(x_test)

In [43]:
(mean_squared_error(y_test,y_pred_lasso))**0.5

24718.96856079639

In [44]:
r2_score(y_test,y_pred_lasso)

0.7928875562183864